import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";

function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Página não encontrada</h2><p className="mt-2 text-sm">O endereço informado não existe ou foi alterado.</p><Link to="/" className="mt-6 inline-flex rounded-md bg-green-700 px-4 py-2 text-white">Voltar ao início</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-screen items-center justify-center px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">Esta página não carregou</h1><p className="mt-2 text-sm">Ocorreu um problema. Tente novamente.</p><button onClick={()=>{router.invalidate();reset()}} className="mt-6 rounded-md bg-green-700 px-4 py-2 text-white">Tentar novamente</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Limpa Fossa Icoaraci 24h | Desentupimento e Hidrojateamento"},{name:"description",content:"Limpa Fossa em Icoaraci 24 horas. Limpeza de fossa, sucção de resíduos, desentupimento e hidrojateamento. Solicite atendimento pelo WhatsApp."},{name:"author",content:"Limpa Fossa Icoaraci"},{name:"robots",content:"index, follow, max-image-preview:large"},{property:"og:title",content:"Limpa Fossa Icoaraci — Atendimento 24h"},{property:"og:description",content:"Limpeza de fossa, desentupimento e hidrojateamento em Icoaraci. Atendimento rápido pelo WhatsApp."},{property:"og:type",content:"website"},{property:"og:locale",content:"pt_BR"},{property:"og:image",content:"/logo-icoaraci.webp"},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:title",content:"Limpa Fossa Icoaraci — Atendimento 24h"},{name:"twitter:description",content:"Serviços profissionais em Icoaraci, Belém - PA."},{name:"twitter:image",content:"/logo-icoaraci.webp"},{name:"theme-color",content:"#064525"}],links:[{rel:"preload",href:"/hero-icoaraci.webp",as:"image",fetchPriority:"high"},{rel:"preload",href:"/fonts/sarabun-800.ttf",as:"font",type:"font/ttf",crossOrigin:"anonymous"},{rel:"stylesheet",href:appCss},{rel:"icon",href:"/logo-icoaraci.webp",type:"image/webp"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt-BR"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}