import { createFileRoute } from "@tanstack/react-router";
import { Check, MapPin, Phone, RefreshCw } from "lucide-react";
export const Route=createFileRoute("/")({component:Index});
const wa="https://wa.me/5591980909686?text=Ol%C3%A1%21%20Encontrei%20a%20Limpa%20Fossa%20Icoaraci%20pelo%20Google%20e%20gostaria%20de%20solicitar%20um%20or%C3%A7amento.";
const services=[
["Limpeza de Fossa Séptica","Caminhão limpa fossa para sucção completa e descarte seguro.","Realizamos a limpeza completa de fossas sépticas, caixas de inspeção e reservatórios com caminhão de sucção de alta potência.",["Remoção completa","Eliminação de odores","Prevenção de danos","Descarte correto","Atendimento rápido"]],
["Sucção de Resíduos e Efluentes","Remoção técnica de resíduos líquidos e sólidos","Sucção de caixas de gordura, tanques, poços e reservatórios com equipamentos de alta capacidade.",["Alta eficiência","Evita contaminação","Processo seguro","Atendimento rápido"]],
["Desentupimento de Pia","Solução rápida sem quebra","Utilizamos sondas elétricas para remover gordura e resíduos acumulados nas tubulações.",["Sem quebra","Remoção completa","Resultado imediato"]],
["Desentupimento de Ralo","Desobstrução completa de ralos internos e externos","Eliminamos bloqueios causados por sujeira, sabão e resíduos utilizando equipamentos profissionais.",["Fluxo normal da água","Evita alagamentos","Garante fluxo contínuo","Sem danos"]],
["Desentupimento de Vaso Sanitário","Técnica segura e eficiente","Utilizamos pressão controlada para remover obstruções sem danificar o vaso.",["Sem sujeira","Sem danos à louça","Execução rápida","Ideal para residências e condomínios"]],
["Desentupimento de Esgoto","Limpeza profunda com hidrojato","Realizamos limpeza da rede de esgoto com jato de alta pressão, removendo resíduos e incrustações.",["Solução duradoura","Elimina odores","Limpeza completa","Casas, comércios e condomínios"]],
["Desentupimento de Caixa de Gordura","Limpeza essencial para evitar entupimentos","Removemos gordura acumulada e resíduos, garantindo funcionamento correto da caixa.",["Evita entupimentos","Reduz odores","Reduz risco de infestação","Descarte correto"]],
["Hidrojateamento Profissional","Alta pressão para limpeza profunda","Utilizamos hidrojato para limpar tubulações, fossas e redes pluviais sem danificar o sistema.",["Limpeza profunda","Alta eficiência","Resultado duradouro"]],
["Limpeza de Banheiro Químico","Higienização completa e segura","Realizamos limpeza de banheiros químicos com sucção, higienização e reposição de produtos.",["Higiene total","Ideal para eventos","Serviço rápido e seguro","Descarte correto"]],
["Manutenção Preventiva","Evite emergências e gastos desnecessários","Planos periódicos de limpeza e inspeção para manter o sistema funcionando corretamente.",["Reduz problemas","Evita custos altos","Aumenta durabilidade"]]] as const;
const faqs=[["Vocês atendem 24h em Icoaraci?","Sim. Funcionamos 24h por dia, incluindo finais de semana e feriados."],["O orçamento tem custo?","Não. Realizamos avaliação e orçamento gratuito antes da execução."],["Vocês também fazem desentupimento?","Sim. Atendemos pia, ralo, vaso, esgoto e caixa de gordura."],["O serviço causa quebra ou sujeira?","Não. Utilizamos técnicas modernas para uma execução limpa e rápida."],["O desentupimento é sem quebra?","Sim. Nossas técnicas são não invasivas."],["Atendem empresas e condomínios?","Sim. Atendemos residências, comércios, indústrias, obras e condomínios."]] as const;
const WhatsAppIcon=()=> <svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16.04 3C8.86 3 3.02 8.82 3.02 16c0 2.29.6 4.53 1.74 6.5L3 29l6.67-1.75A13 13 0 0 0 16.03 29h.01c7.17 0 13.02-5.83 13.02-13S23.22 3 16.04 3Zm0 23.8h-.01a10.8 10.8 0 0 1-5.5-1.5l-.4-.23-3.96 1.04 1.06-3.86-.25-.4A10.77 10.77 0 0 1 5.32 16c0-5.92 4.82-10.74 10.73-10.74A10.75 10.75 0 0 1 26.78 16c0 5.92-4.82 10.74-10.74 10.74Zm5.89-8.05c-.32-.16-1.91-.94-2.2-1.05-.3-.11-.52-.16-.73.16-.22.32-.84 1.05-1.03 1.27-.19.21-.38.24-.7.08-.33-.16-1.37-.5-2.61-1.61a9.76 9.76 0 0 1-1.81-2.25c-.19-.32-.02-.5.14-.66.15-.14.33-.38.49-.57.16-.19.21-.32.32-.54.11-.21.06-.4-.03-.56-.08-.16-.73-1.76-1-2.41-.27-.64-.54-.55-.73-.56h-.63c-.22 0-.57.08-.87.4-.3.32-1.14 1.11-1.14 2.71s1.17 3.15 1.33 3.37c.16.21 2.3 3.51 5.57 4.92.78.34 1.39.54 1.86.69.78.25 1.49.21 2.05.13.63-.09 1.91-.78 2.18-1.54.27-.76.27-1.41.19-1.54-.08-.14-.3-.22-.62-.38Z"/></svg>;
const Btn=({children}:{children:string})=><a className="ref-btn" href={wa} target="_blank" rel="noreferrer">{children}<WhatsAppIcon/></a>;
function Index(){return <main><header className="ref-header"><div className="ref-container"><img src="/logo-icoaraci-transparente.png" alt="Limpa Fossa Icoaraci"/><a className="ref-btn" href={wa} target="_blank" rel="noreferrer">WhatsApp 24h! <WhatsAppIcon/></a></div></header>
<section className="ref-hero"><div className="ref-container hero-inner"><div><span className="ref-kicker">LIMPA FOSSA ICOARACI — ATENDIMENTO 24H</span><h1>Limpeza de Fossa,<br/>Desentupimento e<br/>Hidrojateamento em Icoaraci</h1><p>A <strong>Limpa Fossa Icoaraci</strong> oferece serviços completos de limpeza de fossa, sucção, hidrojateamento e desentupimento 24h.<br/>Atendemos toda a região com rapidez, equipe experiente e execução segura para residências, comércios e indústrias.</p><Btn>ORÇAMENTO IMEDIATO!</Btn></div></div></section>
<section className="ref-light services"><div className="ref-container"><div className="ref-title center"><span className="ref-kicker">SERVIÇOS ESPECIALIZADOS DE DESENTUPIMENTO</span><h2>Serviços Técnicos em Limpa Fossa e<br/>Desentupimento — Atuação<br/>Completa para Icoaraci e região</h2><p>A <strong>Limpa Fossa Icoaraci</strong> oferece soluções completas em <strong>limpeza de fossa séptica, sucção de resíduos, hidrojateamento e serviços de desentupidora 24h.</strong> Trabalhamos com caminhão limpa fossa e equipamentos modernos para garantir execução rápida, segura e sem transtornos.</p><p>Atendemos residências, comércios, indústrias, obras e condomínios em Icoaraci e região.</p></div><div className="service-grid">{services.map(([title,sub,text,benefits])=><article className="ref-card" key={title}><Check/><h3>{title}</h3><strong>{sub}</strong><p>{text}</p><b>Benefícios:</b><ul>{benefits.map(x=><li key={x}>{x}</li>)}</ul><Btn>Faça orçamento aqui</Btn></article>)}</div></div></section>
<section className="ref-dark split"><div className="ref-container split-grid"><img src="https://limpafossabelem24h.com.br/wp-content/uploads/2025/11/desentupidora-10.webp"/><div><span className="ref-kicker">ATENDIMENTO ESPECIALIZADO 24H</span><h2>Quanto custa um serviço de Limpa Fossa em Icoaraci?</h2><p>Trabalhamos com total transparência. Os valores variam conforme o tipo de serviço, volume de resíduos e acesso ao local.</p><p>Oferecemos orçamento gratuito, com análise técnica rápida para indicar a melhor solução.</p><p>Todos os serviços incluem orientação preventiva e garantia de execução.</p><strong>Solicite seu orçamento com atendimento imediato!</strong><Btn>SOLICITAR ORÇAMENTO</Btn></div></div></section>
<section className="ref-light areas"><div className="ref-container"><div className="gallery"><img src="https://limpafossabelem24h.com.br/wp-content/uploads/2025/11/desentupidora-10.webp"/><img src="https://limpafossabelem24h.com.br/wp-content/uploads/2025/11/desentupidora-7.webp"/><img src="https://limpafossabelem24h.com.br/wp-content/uploads/elementor/thumbs/desentupidora-13-1-re7pbtog2vqi1runprsodatai4l7sol4xritdhzr9s.webp"/></div><div className="areas-copy"><span className="ref-kicker">TODOS OS DIAS RESOLVENDO SEU PROBLEMA</span><h2>Áreas Atendidas —<br/>Atendimento 24h</h2><h3>Chegamos rápido até você com caminhão próprio e equipe especializada</h3><p>Contamos com caminhão limpa fossa próprio, equipamentos de alta capacidade e equipe técnica preparada para atender com agilidade.</p><p>Nossa base está localizada na <strong>Tv. Souza Franco, 844 – Agulha</strong>, facilitando o deslocamento rápido.</p><p>Trabalhamos 24 horas por dia, inclusive aos finais de semana e feriados.</p><strong>Regiões atendidas:</strong><div className="pins">{["Icoaraci","Agulha","Cruzeiro","Ponta Grossa","Maracacuera","Paracuri","Campina de Icoaraci","Águas Negras","Tenoné","Outeiro"].map(x=><span key={x}><MapPin/> {x}</span>)}</div><Btn>FALE COM NOSSO ESPECIALISTA</Btn></div></div></section>
<section className="ref-dark process"><div className="ref-container"><span className="ref-kicker">COMO TRABALHAMOS NA PRÁTICA</span><h2>Veja como funciona<br/>nosso processo de<br/>limpeza de fossa e<br/>desentupimento</h2><h3>Clareza e transparência em cada etapa.</h3><div className="process-grid">{[["Diagnóstico técnico","Identificação do problema"],["Definição da técnica","Escolha do método ideal"],["Execução rápida","Sem sujeira e sem quebra"],["Teste final","Verificação completa"]].map(([a,b])=><div key={a}><RefreshCw/><strong>{a}</strong><span>{b}</span></div>)}</div></div></section>
<section className="ref-light why"><div className="ref-container"><span className="ref-kicker">DESENTUPIDORA 24 HORAS</span><h2>Por que escolher a<br/>Limpa Fossa Icoaraci</h2><h3>Segurança e qualidade em cada atendimento</h3><div className="why-list">{["Atendimento 24h","Orçamento gratuito","Pagamento facilitado","Equipamentos modernos","Descarte responsável","Serviço rápido"].map(x=><div key={x}>{x}</div>)}</div><div className="mission-grid">{[["Missão","Prestar serviços com excelência, rapidez e responsabilidade, garantindo segurança e satisfação."],["Visão","Ser referência em Icoaraci e região pela qualidade, agilidade e compromisso ambiental."],["Valores","Ética, transparência, compromisso com o cliente, responsabilidade ambiental e qualidade técnica."]].map(([a,b])=><article key={a}><Check/><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
<section className="banner"><div className="ref-container"><h2>Chega de mau cheiro, risco de<br/>transbordamento e dor de cabeça —<br/>resolvemos hoje. Atendimento imediato com<br/>equipe técnica e garantia.</h2><p>Atendimento rápido e sem sujeira — fale com um especialista agora.</p><Btn>FALAR COM UM ESPECIALISTA</Btn></div></section>
<section className="ref-light faq"><div className="ref-container"><div className="ref-title center"><span className="ref-kicker">[ FAQ ]</span><h2>Perguntas frequentes sobre limpa fossa e<br/>desentupimento em Icoaraci</h2></div><div className="faq-grid">{faqs.map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></section>
<footer className="ref-footer"><div className="ref-container footer-top"><img src="/logo-icoaraci-transparente.png" alt="Limpa Fossa Icoaraci"/><div><h3>Contato</h3><p>Limpa Fossa Icoaraci</p><p><MapPin/> Tv. Souza Franco, 844 - Agulha, Belém - PA</p><p><Phone/> (91) 98090-9686</p><p>Horário de funcionamento: Aberto 24 horas</p></div><iframe title="Localização da Limpa Fossa Icoaraci" src="https://www.google.com/maps?q=Tv.%20Souza%20Franco%2C%20844%20-%20Agulha%2C%20Bel%C3%A9m%20-%20PA%2C%2066812-430&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><div className="ref-container copyright">2026 – Limpa Fossa Icoaraci. Todos os direitos reservados | Desenvolvido por Agência Digitales 360.</div></footer><a className="float-wa" href={wa} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp"><WhatsAppIcon/></a></main>}